postgresql:
  enabled: true
  postgresqlDatabase: readings
  postgresqlUsername: postgres
  postgresqlPassword: postgres
kafka:
  enabled: false
replicaCount: 1
config:
  port: 80
  logLevel: info
  apiReadingsLimit: 10000
  dbName: readings
  dbPort: 5432
  kafkaLogLevel: 'info'
  kafkaBrokers: 'kafka:9092'
  externalPostgresql: null
  kafkaReadingsTopic: readings
  kafkaReadingsNotificationsTopic: reading-notifications
  readingsReplicationFactor: 1
  readingsPartitions: 5
image:
  repository: ghcr.io/digicatapult/wasp-reading-service
  pullPolicy: IfNotPresent
  tag: 'v0.0.18'
  pullSecrets: ['ghcr-digicatapult']
ingress:
  path: /v1/thing/[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}/dataset
