{{- $fullName := include "wasp-reading-service.fullname" . -}}
  {{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "wasp-reading-service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: {{ $ingressPath }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
